version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}  # This will use the BOT_TOKEN from your .env or host environment
    volumes:
      - .:/app  # This ensures that local changes reflect inside the container (optional if needed)
    restart: unless-stopped  # Automatically restart the bot unless manually stopped
